/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Button = ({ variant, label }) => {
  return <button className={`button ${variant}`}>{label}</button>;
};

export default Button;
