/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Logo from "./Logo";
import Navigation from "./Navigation";
import Button from "./Button";

const Header = () => {
  return (
    <header className="header">
      <div className="container">
        <div className="content">
          <Logo />
          <div className="links-actions">
            <Navigation />
            <div className="actions">
              <Button variant="primary" label="Sign up" />
            </div>
          </div>
        </div>
      </div>
    </header>
  );
};

export default Header;
