/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Hero from "./Hero";
import Certifications from "./Certifications";
import ValueProposition from "./ValueProposition";
import Services from "./Services";
import OurServices from "./OurServices";
import Testimonials from "./Testimonials";
import BlogSection from "./BlogSection";
import Footer from "./Footer";
import './styles.css'

const HomePage = () => {
  return (
    <div className="home-page">
      <Header />
      <main>
        <Hero />
        <Certifications />
        <ValueProposition />
        <Services />
        <OurServices />
        <Testimonials />
        <BlogSection />
      </main>
      <Footer />
    </div>
  );
};

export default HomePage;
