/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Logo = () => {
  return (
    <div className="logo-container">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/749e7bbc6400295e7534bd260998047037d921a9ebb80679d4e903f6ffd98401?apiKey=0dc91187d1fc4cb3931d3d7b27a4a892&"
        alt="Company logo icon"
        className="logo-icon"
      />
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/9922471d8b9c4158c8ce5c9064643d3d1f53a993633fa5b7bb6c1996911d2d51?apiKey=0dc91187d1fc4cb3931d3d7b27a4a892&"
        alt="Company logo text"
        className="logo-text"
      />
    </div>
  );
};

export default Logo;
