/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FooterLinks from "./FooterLinks";
import SocialLinks from "./SocialLinks";

const Footer = () => {
  const quickLinks = ["About Us", "Services", "FAQs", "Careers", "Contact Us"];
  const contactInfo = ["Phone number", "Email Address", "Office Location"];

  return (
    <footer className="footer">
      <div className="container">
        <div className="footer-content">
          <div className="footer-logo">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/d57982656061e181b3b95853f2b04da01a9bab2b04b3d5caa8dcbfe697fd3e07?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892"
              className="logo-icon"
              alt="Company icon"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/7fdf952dc6fee274fcdfd61516cf18f673cf877eb4f379c608af1624b6cc42c3?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892"
              className="logo-text"
              alt="Company name"
            />
          </div>
          <div className="footer-links">
            <FooterLinks title="Quick Links" links={quickLinks} />
            <FooterLinks title="Contact Information" links={contactInfo} />
            <SocialLinks />
          </div>
        </div>
        <div className="footer-bottom">
          <div className="divider" />
          <div className="footer-info">
            <div className="legal-links">
              <a href="#" className="legal-link">
                Terms of Service
              </a>
              <a href="#" className="legal-link">
                Privacy Policy
              </a>
            </div>
            <p className="copyright">
              © Copyright 2024 Orbit All rights reserved.
            </p>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
