/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Link = ({ text, href, hasDropdown }) => (
  <a href={href} className="nav-link">
    {text}
    {hasDropdown && (
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/745f4a325798408d80543bbacf1852135593f5c0514bd614a697a7386fbb93c1?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892"
        className="dropdown-icon"
        alt=""
      />
    )}
  </a>
);

export default Link;
