/**
 * This code was generated by Builder.io.
 */
import React from "react";

const PrimaryButton = ({ text }) => (
  <button className="primary-button">{text}</button>
);

export default PrimaryButton;
