/**
 * This code was generated by Builder.io.
 */
import React from "react";
import './navigation.css'
import Button from "../Button";

const Navigation = () => {
  const navItems = [
    { label: "About Us", link: "#" },
    { label: "Services", link: "#" },
    { label: "FAQs", link: "#" },
    { label: "Contact Us", link: "#" },
    { label: "Resources", link: "#", hasDropdown: true },
    // { label: "Sign Up", variant: "" },
    // { label: "Login", variant: "" }

  ];


  return (
    <nav className="navigation">
      {navItems.map((item, index) => (
        <div key={index} className="nav-item">
          <a href={item.link} className="nav-link">
            {item.label}
          </a>
          {item.hasDropdown && (
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/745f4a325798408d80543bbacf1852135593f5c0514bd614a697a7386fbb93c1?apiKey=0dc91187d1fc4cb3931d3d7b27a4a892&"
              alt="Dropdown indicator"
              className="dropdown-icon"
            />
          )}
          {/* {item.label === "Sign Up" && ( */}

       
            
          {/* )} */}

        </div>
      ))}
           <Button label={"Login"} variant={"secondary"}/>
           <Button label={"Sign up"} variant={"primary"}/>
    </nav>
  );
};

export default Navigation;
