/**
 * This code was generated by Builder.io.
 */
import React from "react";
import mock from '../../../images/mock.png'
import frm1 from '../../../images/frm1.png'

const DigitalExperience = () => {
  // const features = [
  //   {
  //     number: "1",
  //     title: "User Friendly Interface",
  //     description:
  //       "Ensuring easy navigation and intuitive design for a seamless user experience.",
  //   },
  //   {
  //     number: "2",
  //     title: "24/7 Access",
  //     description:
  //       "Providing round-the-clock access to our digital lending platforms.",
  //   },
  //   {
  //     number: "3",
  //     title: "Enhance Security",
  //     description:
  //       "Implementing robust data protection measures and secure transaction protocols.",
  //   },
  // ];

  return (
    // <section className="digital-experience">
    //   <div className="experience-content">
    //     <h2 className="section-title">Technology</h2>
    //     <h3 className="section-subtitle">Seamless Digital Experience</h3>
    //     <div className="feature-list">
    //       {features.map((feature, index) => (
    //         <div key={index} className="feature-item">
    //           <span className="feature-number">{feature.number}</span>
    //           <div className="feature-details">
    //             <h4 className="feature-title">{feature.title}</h4>
    //             <p className="feature-description">{feature.description}</p>
    //           </div>
    //         </div>
    //       ))}
    //     </div>
    //   </div>
    //   <div className="experience-image">
    //     <img
    //       src="https://cdn.builder.io/api/v1/image/assets/TEMP/67a68884157b457a1205a2581dcdcd94a08b0b2a1b48cd61e8998c441cbd2e00?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892"
    //       alt="Digital experience illustration"
    //       className="experience-img"
    //     />
    //   </div>
    // </section>4

    <div className="digital-container">
        <div className="digital-title">
          <h2>Technology</h2>
          <h3>Seamless Digital Experience</h3>
        </div>
        <div className="digital-section">
        <div>
          <img src={mock} alt="" />
        </div>
        <div className="dig">
          <ol>
            <li>
              <h4>User Friendly Interface</h4>
              <p>Ensuring easy navigation and intuitive design for a <br/>seamless user experience.</p>
            </li>
            <img src={frm1} alt="" />
            <li>
              <h4>24/7 Access</h4>
              <p>Providing round-the-clock access to our digital lending <br/>platforms.</p>
            </li>
            <img src={frm1} alt="" />
            <li>
              <h4>Enhance Security</h4>
              <p>Implementing robust data protection measures and <br/>secure transaction protocols.</p>
            </li>
          </ol>
        </div>
        </div>
    </div>
  );
};

export default DigitalExperience;
