/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "../../components/Header";

const Header = () => {
  return (
    <header className="header">
      <div className="container">
        <div className="content">
          <div className="logo-wrapper">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/c4917842099c3dfca459af7bf169c84eed359704ac6d211ac1cf7a61a11d9a56?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892"
              className="logo-icon"
              alt="Company logo icon"
            />
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/559e5f8a2f69e5175afb31f16c27fe9c969385c91b8289bb5b654aeb909a359d?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892"
              className="logo-text"
              alt="Company logo text"
            />
          </div>
          <nav className="navigation">
            <ul className="nav-list">
              <li>
                <a href="#about" className="nav-link">
                  About Us
                </a>
              </li>
              <li>
                <a href="#services" className="nav-link nav-link-active">
                  Services
                </a>
              </li>
              <li>
                <a href="#faqs" className="nav-link">
                  FAQs
                </a>
              </li>
              <li>
                <a href="#contact" className="nav-link">
                  Contact Us
                </a>
              </li>
              <li className="resources-wrapper">
                <a href="#resources" className="nav-link">
                  Resources
                </a>
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/745f4a325798408d80543bbacf1852135593f5c0514bd614a697a7386fbb93c1?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892"
                  className="dropdown-icon"
                  alt="Dropdown icon"
                />
              </li>
            </ul>
          </nav>
          <div className="cta-wrapper">
            <button className="cta-button">Sign up</button>
          </div>
        </div>
      </div>
    </header>
  );
};

export default Header;
