/**
 * This code was generated by Builder.io.
 */
import React from "react";

const InvestmentCard = ({ title, amount, percentageChange, imageSrc }) => {
  return (
    <div className="investment-card">
      <img
        src={imageSrc}
        alt={`${title} illustration`}
        className="investment-img"
      />
      <div className="investment-details">
        <div className="investment-info">
          <h3 className="investment-title">{title}</h3>
          <p className="investment-amount">{amount}</p>
          <div className="investment-change">
            <span className="badge">
              <img
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/ccce3b42cfe4434a18fbf41e967d4de11106e8244baf9cb749cfbae8c732db85?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892"
                alt="Trend icon"
                className="trend-icon"
              />
              <span className="percentage">{percentageChange}</span>
            </span>
            <span className="period">this month</span>
          </div>
        </div>
        <img
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/35d9f43744e8511f5b074be0d4251d2dc5d9a9ea44f8c7ee11a7fe0ce875626b?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892"
          alt="Graph illustration"
          className="graph-img"
        />
      </div>
    </div>
  );
};

export default InvestmentCard;
