/**
 * This code was generated by Builder.io.
 */
import React from "react";

const ServiceCard = ({
  title,
  description,
  eligibilityCriteria,
  applicationProcess,
  ctaText,
  imageSrc,
  imageAlt,
}) => {
  return (
    <div className="service-card">
      <div className="service-info">
        <span className="service-tag">{title}</span>
        <h2 className="service-name">{description}</h2>
        <h3 className="section-title">Description</h3>
        <p className="section-content">{eligibilityCriteria}</p>
        <h3 className="section-title">Eligibility Criteria</h3>
        <ul className="eligibility-list">
          {eligibilityCriteria.map((criteria, index) => (
            <li key={index}>{criteria}</li>
          ))}
        </ul>
        <h3 className="section-title">Application Process</h3>
        <ol className="application-steps">
          {applicationProcess.map((step, index) => (
            <li key={index}>{step}</li>
          ))}
        </ol>
        <a href="#apply" className="cta-link">
          {ctaText}
        </a>
      </div>
      <div className="service-image">
        <img src={imageSrc} alt={imageAlt} className="service-img" />
      </div>
    </div>
  );
};

export default ServiceCard;
