/**
 * This code was generated by Builder.io.
 */
import React from "react";

const TechnologySection = () => {
  const techFeatures = [
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/c40960eafada5ff4a3f71efd60c945967b0cfb94baf454f175601c6bdbb3aa61?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892",
      title: "Personalised Loan Offer",
      description:
        "Utilizing customer segmentation and dynamic pricing to offer personalized loan solutions",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/a56931802612980d38258c1681fdc7d52b378e56512fd302c3f5da19cfb0a98d?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892",
      title: "Automated Credit Score",
      description:
        "Using alternative data sources and machine learning models to provide accurate and fair credit scoring",
    },
    {
      icon: "https://cdn.builder.io/api/v1/image/assets/TEMP/85f361f0cd8f89ce32ee4f56d67f0fbdb92aebc893931ba47d34bd06de230fa7?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892",
      title: "Fraud Detection",
      description:
        "Implementing real-time monitoring and behavioral analysis to prevent and detect fraudulent activities.",
    },
  ];

  return (
    <section className="technology-section">
      <h2 className="section-title">Technology</h2>
      <h3 className="section-subtitle">Ai Driven Solution</h3>
      <div className="tech-features">
        {techFeatures.map((feature, index) => (
          <div key={index} className="tech-feature">
            <img
              src={feature.icon}
              alt={`${feature.title} icon`}
              className="feature-icon"
            />
            <div className="feature-content">
              <h4 className="feature-title">{feature.title}</h4>
              <p className="feature-description">{feature.description}</p>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
};

export default TechnologySection;
