/**
 * This code was generated by Builder.io.
 */
import React from "react";
import FAQItem from "./FAQItem";

const faqData = [
  {
    question: "What is Orbit Financial Services",
    answer:
      "Orbit Financial Services Limited (OFSL) was founded with the mission to empower Nigerian small businesses by providing access to funds through innovative and customer-centric financial solutions.",
  },
  // Add more FAQ items here
];

const FAQList = () => (
  <div className="faq-list">
    {faqData.map((faq, index) => (
      <FAQItem key={index} question={faq.question} answer={faq.answer} />
    ))}
  </div>
);

export default FAQList;
