/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Hero from "./Hero";
import FAQTabs from "./FAQTabs";
import FAQList from "./FAQList";
import ContactCTA from "./ContactCTA";
import Footer from "./Footer";
import '../styles/globals.css'

const FAQPage = () => (
  <div className="faq-page">
    <Header />
    <main>
      <Hero />
      <section className="faq-section">
        <FAQTabs />
        <FAQList />
      </section>
      <ContactCTA />
    </main>
    <Footer />
  </div>
);

export default FAQPage;
