/**
 * This code was generated by Builder.io.
 */
import React from "react";

const FAQTabs = () => (
  <nav className="faq-tabs">
    <button className="tab-button active">All FAQs</button>
    <button className="tab-button">Microloans</button>
    <button className="tab-button">Investment</button>
    <button className="tab-button">Invoicing</button>
    <button className="tab-button">Loan Repayment</button>
    <button className="tab-button">Sustainability</button>
  </nav>
);

export default FAQTabs;
