/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Footer = () => (
  <footer className="site-footer">
    <div className="container">
      <div className="footer-content">
        <div className="footer-logo">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/b2be47b0bd08ed728771cc502def1fdae17afd04af17773c2c889070a8a30ce9?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892"
            alt="Company logo"
            className="logo"
          />
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/99f3430b293913332110c8cb777af64b73c8dd74c0c8c3a8c15aabc9eee79ddb?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892"
            alt="Company name"
            className="company-name"
          />
        </div>
        <div className="footer-links">
          <div className="footer-column">
            <h3 className="footer-heading">Quick Links</h3>
            <ul className="footer-list">
              <li>
                <a href="#" className="footer-link">
                  About Us
                </a>
              </li>
              <li>
                <a href="#" className="footer-link">
                  Services
                </a>
              </li>
              <li>
                <a href="#" className="footer-link">
                  FAQs
                </a>
              </li>
              <li>
                <a href="#" className="footer-link">
                  Careers
                </a>
              </li>
              <li>
                <a href="#" className="footer-link">
                  Contact Us
                </a>
              </li>
            </ul>
          </div>
          <div className="footer-column">
            <h3 className="footer-heading">Contact Information</h3>
            <ul className="footer-list">
              <li>
                <a href="#" className="footer-link">
                  Phone number
                </a>
              </li>
              <li>
                <a href="#" className="footer-link">
                  Email Address
                </a>
              </li>
              <li>
                <a href="#" className="footer-link">
                  Office Location
                </a>
              </li>
            </ul>
          </div>
          <div className="footer-column">
            <h3 className="footer-heading">Follow us</h3>
            <div className="social-icons">
              <a href="#" className="social-link">
                <img
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/4d19504aab822b323515c33dba56b2bcffeaf7db0d84977a149aa430bccc9dbe?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892"
                  alt="Facebook"
                />
              </a>
              <a href="#" className="social-link">
                <img
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/ccf2b20cf2b49e22b53e8e8ad308276747c0d7193328de60b42aa57f11e3f3d2?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892"
                  alt="Twitter"
                />
              </a>
              <a href="#" className="social-link">
                <img
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/1e8453e9bdfb9c680bba3da68c416bc8bebc0eed54c0195dec7f90aa28d778df?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892"
                  alt="Instagram"
                />
              </a>
              <a href="#" className="social-link">
                <img
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/a93acd8f4a121c9972c5712a5131c6a85d3b8bd94771839805308c12f88fef52?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892"
                  alt="LinkedIn"
                />
              </a>
            </div>
          </div>
        </div>
      </div>
      <div className="footer-bottom">
        <div className="footer-legal">
          <a href="#" className="legal-link">
            Terms of Service
          </a>
          <a href="#" className="legal-link">
            Privacy Policy
          </a>
        </div>
        <p className="copyright">© Copyright 2024 Orbit All rights reserved.</p>
      </div>
    </div>
  </footer>
);

export default Footer;
