/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Link from "./Link";

const Header = () => (
  <header className="site-header">
    <div className="container">
      <div className="header-content">
        <div className="logo-container">
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/b2be47b0bd08ed728771cc502def1fdae17afd04af17773c2c889070a8a30ce9?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892"
            alt="Company logo"
            className="logo"
          />
          <img
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/a46972457b3f9a4e4b17ad3a0c50b446a47b1ff4b44db751c25344134dc6c2b9?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892"
            alt="Company name"
            className="company-name"
          />
        </div>
        <nav className="main-nav">
          <Link text="About Us" />
          <Link text="Services" />
          <Link text="FAQs" />
          <Link text="Contact Us" />
          <div className="resources-dropdown">
            <Link text="Resources" />
            <img
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/745f4a325798408d80543bbacf1852135593f5c0514bd614a697a7386fbb93c1?placeholderIfAbsent=true&apiKey=0dc91187d1fc4cb3931d3d7b27a4a892"
              alt="Dropdown arrow"
              className="dropdown-arrow"
            />
          </div>
        </nav>
        <div className="cta-container">
          <button className="cta-button">Sign up</button>
        </div>
      </div>
    </div>
  </header>
);

export default Header;
